# Generated by Django 4.2 on 2024-12-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Promo Code')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('point', models.IntegerField(verbose_name='Points')),
                ('used_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Used By')),
            ],
            options={
                'verbose_name': 'Promocode',
                'verbose_name_plural': 'Promocodes',
            },
        ),
    ]
