# Generated by Django 4.2 on 2024-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=100, unique=True)),
                ("fullname", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("is_registered", models.BooleanField(default=False)),
                ("points", models.IntegerField(default=5)),
            ],
        ),
    ]
